# ============================================================
# Training Arguments for HuggingFace Trainer
# Model: facebook/bart-large-cnn fine-tuned on SAMSum
# ============================================================
TrainingArguments:
  num_train_epochs: 3
  warmup_steps: 500
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  weight_decay: 0.01
  logging_steps: 50
  eval_strategy: steps
  eval_steps: 500
  save_steps: 500
  gradient_accumulation_steps: 8
  learning_rate: 2.0e-5
  fp16: true
  save_total_limit: 3
  load_best_model_at_end: true
  report_to: none


# ============================================================
# Data Transformation Parameters
# ============================================================
DataTransformation:
  max_input_length: 1024
  max_target_length: 128
  text_column: dialogue
  summary_column: summary


# ============================================================
# Model Evaluation Parameters
# ============================================================
ModelEvaluation:
  batch_size: 8
  max_input_length: 1024
  max_target_length: 128
  text_column: dialogue
  summary_column: summary

